#
# Jekyll configuration
#
permalink: /blog/:year/:month/:day/:title 

#
# Site configuration
#
BASE_PATH : http://dandelion.github.io
ASSET_PATH : false
analytics_google_tracking_id : 'UA-33818546-8'

#
# Blog configuration
#
title : Dandelion Project
tagline: Extensible web library for funnier web development
author :
  name : Dandelion Team
  email : dandelion-devteam@googlegroups.com
  github : dandelion
  twitter : dandelion_proj
production_url : http://dandelion.github.io
atom_path : /blog/atom.xml
rss_path : /blog/rss.xml
archive_path: /blog/archive.html
categories_path : /blog/categories.html
tags_path : /blog/tags.html 

#
# Dandelion data
#
dandelion :
  team: "Dandelion Team 2013"
  components:
    core:
      name: core
      version: 0.2.0
      url: dandelion
      breadcrumb: Dandelion
      sources: dandelion
    datatables:
      name: datatables
      version: 0.8.14
      url: datatables
      breadcrumb: Dandelion-Datatables
      sources: dandelion-datatables
    webanalytics:
      name: webanalytics
      version: 0.2.1
      url: webanalytics
      breadcrumb: Dandelion-Webanalytics
      sources: dandelion-webanalytics
