encoding: utf-8

# Site settings
title: Dandelion Project
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Dandelion is a free and Open Source Java framework aimed at making web development simpler in JVM-based environments.
  It helps to manipulate the web assets (JS, CSS) in different ways: assets organization in a bundle graph and classical optimizations like minification, compression or caching.
  It also facilitates the integration of powerful JavaScript libraries thanks to a set of extensible components.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dandelion.github.io" # the base hostname & protocol for your site
twitter: https://twitter.com/dandelion_proj
forum: http://dandelion.48353.n6.nabble.com/

#
# Blog
#
permalink: /blog/:year/:month/:day/:title

#
# General
#
gaid : 'UA-33818546-8'

#
# AsciiDoctor configuration
#
asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=coderay
