encoding: utf-8

# Site settings
title: Dandelion Project
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dandelion.github.io/" # the base hostname & protocol for your site
twitter: https://twitter.com/dandelion_proj
forum: http://dandelion.48353.n6.nabble.com/

#
# Blog
#
permalink: /blog/:year/:month/:day/:title

#
# General
#
gaid : 'UA-33818546-8'

#
# AsciiDoctor configuration
#
asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=coderay
