#
# Jekyll configuration
#
permalink: /blog/:year/:month/:day/:title 
pygments: true

#
# Site configuration
#
gaid : 'UA-33818546-8'

#
# Blog configuration
#
title : Dandelion Project
tagline: Extensible web library making web development simpler
author :
  name : Dandelion Team
  email : dandelion-devteam@googlegroups.com
  github : dandelion
  twitter : dandelion_proj
production_url : http://dandelion.github.io
atom_path : /blog/atom.xml
rss_path : /blog/rss.xml
archive_path: /blog/archive.html
categories_path : /blog/categories.html
tags_path : /blog/tags.html 

#
# Dandelion data
#
forum : http://dandelion-forum.48353.x6.nabble.com/
contact : dandelion-devteam@googlegroups.com
twitter : https://twitter.com/dandelion_proj
dandelion :
  team: "Dandelion Team 2013"
  components:
    core:
      name: core
      version: 0.10.1
      url: dandelion
      breadcrumb: Dandelion-Core
      sources: dandelion
      issues: dandelion
      forum: http://dandelion-forum.48353.x6.nabble.com/Dandelion-f295.html
    datatables:
      name: datatables
      version: 0.10.1
      url: datatables
      breadcrumb: Dandelion-Datatables
      sources: dandelion-datatables
      issues: dandelion-datatables
      forum: http://dandelion-forum.48353.x6.nabble.com/Dandelion-Datatables-f3.html
    webanalytics:
      name: webanalytics
      version: 0.2.2
      url: webanalytics
      breadcrumb: Dandelion-Webanalytics
      sources: dandelion-webanalytics
    gua:
      name: gua
      version: 0.1.0-SNAPSHOT
      url: gua
      breadcrumb: Dandelion-GUA
      sources: dandelion-gua
    blog:
      name: blog
