#
# Jekyll configuration
#
permalink: /blog/:year/:month/:day/:title 
auto: true
pygments: true

#
# Site configuration
#
BASE_PATH : http://dandelion.github.io
ASSET_PATH : false
analytics_google_tracking_id : 'UA-33818546-8'

#
# Blog configuration
#
title : Dandelion Project
tagline: Extensible web library for funnier web development
author :
  name : Dandelion Team
  email : dandelion-devteam@googlegroups.com
  github : dandelion
  twitter : dandelion_proj
production_url : http://dandelion.github.com
atom_path : atom.xml
rss_path : rss.xml
archive_path: /blog/archive.html
categories_path : /blog/categories.html
tags_path : /blog/tags.html 

#
# Dandelion data
#
dandelion :
  team: "Dandelion Team 2013"
  components:
    core:
      name: Dandelion-Core
      version: 0.1.0
      url: dandelion
    datatables:
      name: Dandelion-DataTables
      version: 0.8.10
      url: datatables
    webanalytics:
      name: Dandelion-WebAnalytics
      version: 0.1.1
      url: webanalytics
