permalink: /:categories/:year/:month/:day/:title 

auto: true
pygments: true

title : Dandelion Project
tagline: Extensible web library for funnier web development
author :
  name : Dandelion Team
  email : dandelion-devteam@googlegroups.com
  github : dandelion
  twitter : dandelion_proj

production_url : http://dandelion.github.com/blog

analytics_google_tracking_id : 'UA-33818546-8'

BASE_PATH : false
ASSET_PATH : false

atom_path : /atom.xml
rss_path : /rss.xml
archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html